### ISSUE TITLE
Library not work in SPI1 only works in SPI0

### ISSUE THREAD

**Issue by AndresBellero74** [khoih-prog/RP2040_SD#3]
My question is simple, I need it to work on SPI1, so I see I change the pins and it doesn't work, only on SPI0 is it possible to make it selectable?
Thank you so much.

**Comment by khoih-prog** [comment]
Your question is too vague: **no core, no board**. I don't think I'll answer this type of question next time

Anyway, check [RASPBERRY_PI_PICO pins_arduino.h#L44-L48](https://github.com/arduino/ArduinoCore-mbed/blob/master/variants/RASPBERRY_PI_PICO/pins_arduino.h#L44-L48) and see [**ArduinoCore-mbed** core](https://github.com/arduino/ArduinoCore-mbed) **only support 1 SPI**

```
// SPI
#define PIN_SPI_MISO  (4u)
#define PIN_SPI_MOSI  (3u)
#define PIN_SPI_SCK   (2u)
#define PIN_SPI_SS    (5u)
```

while as in [rpipico pins_arduino.h#L17-L26](https://github.com/earlephilhower/arduino-pico/blob/master/variants/rpipico/pins_arduino.h#L17-L26), [**arduino-pico core**](https://github.com/earlephilhower/arduino-pico) **can support 2 SPIs**

```
// SPI
#define PIN_SPI0_MISO  (16u)
#define PIN_SPI0_MOSI  (19u)
#define PIN_SPI0_SCK   (18u)
#define PIN_SPI0_SS    (17u)

#define PIN_SPI1_MISO  (12u)
#define PIN_SPI1_MOSI  (15u)
#define PIN_SPI1_SCK   (14u)
#define PIN_SPI1_SS    (13u)
```

In order to use something special and custom, it requires some more research, even some modifications done by yourself.

---

Moreover, check [**Librrary's Features**](https://github.com/khoih-prog/RP2040_SD#https://github.com/khoih-prog/RP2040_SD#features)

> This library was created as an effort to use SD Card while the `arduino-pico` core still has issue [**SD card FILE_WRITE issue** #214](https://github.com/earlephilhower/arduino-pico/issues/214), which has been fixed from core v1.8.6.
> 
> It's better to use the built-in [SD library](https://github.com/earlephilhower/arduino-pico/tree/master/libraries/SD) for [**Earle Philhower's arduino-pico core v1.8.6+**](https://github.com/earlephilhower/arduino-pico). 
> 
> But if you need to write codes to be used in both [**Arduino-mbed RP2040** core](https://github.com/arduino/ArduinoCore-mbed) and [**Earle Philhower's arduino-pico core**](https://github.com/earlephilhower/arduino-pico) without having to modify the code, you can have the option to use this library.

**Comment by AndresBellero74** [comment]
Thank you very much for the answer, I installed the pico core and the problem was solved. I already read the SD now I have to see how to make the BMP visualize me but it is with another library.
It served me a lot.
sorry for not giving you more info.
I still can't see the bmp but I rescue the attributes, which is a problem with my program that reads the BMP file.
Regards.
![WhatsApp Image 2021-11-09 at 22 20 10](https://user-images.githubusercontent.com/73205398/141032140-17e2419c-77f9-40ad-93c3-0e4572888849.jpeg)

**Comment by khoih-prog** [comment]
I'm glad you've solved the issue and appreciate  you post the good result / experience, which will also help many other users

Regards,

**Comment by AndresBellero74** [comment]
Thanks to your help and the author of the tft_espi library for the raspberry pico I was able to play BMP files with the SD and on the 3.5 "display of the raspberry pi.
I'll pass it to you in case anyone is interested.
This is the project link:
https://github.com/AndresBellero74/Raspberry-PI-PICO-display-RPI35
Regards.
